create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  learning_goal text not null default 'Créer des sites Web',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  xp integer not null default 0 check (xp >= 0),
  nexcoins integer not null default 0 check (nexcoins >= 0),
  streak integer not null default 0 check (streak >= 0),
  last_active_date date,
  daily_goal integer not null default 20 check (daily_goal >= 5),
  daily_completed integer not null default 0 check (daily_completed >= 0),
  recent_course_id text not null default 'html-foundations',
  completed_lessons jsonb not null default '[]'::jsonb,
  mastery jsonb not null default '{}'::jsonb,
  lesson_attempts jsonb not null default '{}'::jsonb,
  lesson_error_tags jsonb not null default '{}'::jsonb,
  project_progress jsonb not null default '{}'::jsonb,
  portfolio_proofs jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  template text not null default 'blank',
  language text not null default 'text',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  path text not null,
  content text not null default '',
  mime_type text,
  size_bytes integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(project_id, path)
);

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  course_id text,
  lesson_id text,
  project_id uuid references public.projects(id) on delete set null,
  xp_delta integer not null default 0,
  nexcoins_delta integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.projects enable row level security;
alter table public.project_files enable row level security;
alter table public.learning_events enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "progress own row" on public.user_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "projects own rows" on public.projects for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "project files own rows" on public.project_files for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "learning events own rows" on public.learning_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', ''))
  on conflict (id) do nothing;

  insert into public.user_progress (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create index if not exists projects_user_updated_idx on public.projects(user_id, updated_at desc);
create index if not exists project_files_project_idx on public.project_files(project_id, path);
create index if not exists learning_events_user_created_idx on public.learning_events(user_id, created_at desc);
